/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WebsitesRouteImport } from './routes/websites'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GamesRouteImport } from './routes/games'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ItemIdRouteImport } from './routes/item.$id'
import { Route as GuidesAndroidOnPcRouteImport } from './routes/guides.android-on-pc'

const WebsitesRoute = WebsitesRouteImport.update({
  id: '/websites',
  path: '/websites',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemIdRoute = ItemIdRouteImport.update({
  id: '/item/$id',
  path: '/item/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesAndroidOnPcRoute = GuidesAndroidOnPcRouteImport.update({
  id: '/guides/android-on-pc',
  path: '/guides/android-on-pc',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/apps': typeof AppsRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/websites': typeof WebsitesRoute
  '/guides/android-on-pc': typeof GuidesAndroidOnPcRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/apps': typeof AppsRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/websites': typeof WebsitesRoute
  '/guides/android-on-pc': typeof GuidesAndroidOnPcRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ai': typeof AiRoute
  '/apps': typeof AppsRoute
  '/contact': typeof ContactRoute
  '/favorites': typeof FavoritesRoute
  '/games': typeof GamesRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/websites': typeof WebsitesRoute
  '/guides/android-on-pc': typeof GuidesAndroidOnPcRoute
  '/item/$id': typeof ItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/apps'
    | '/contact'
    | '/favorites'
    | '/games'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/websites'
    | '/guides/android-on-pc'
    | '/item/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/apps'
    | '/contact'
    | '/favorites'
    | '/games'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/websites'
    | '/guides/android-on-pc'
    | '/item/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ai'
    | '/apps'
    | '/contact'
    | '/favorites'
    | '/games'
    | '/login'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/websites'
    | '/guides/android-on-pc'
    | '/item/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AiRoute: typeof AiRoute
  AppsRoute: typeof AppsRoute
  ContactRoute: typeof ContactRoute
  FavoritesRoute: typeof FavoritesRoute
  GamesRoute: typeof GamesRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WebsitesRoute: typeof WebsitesRoute
  GuidesAndroidOnPcRoute: typeof GuidesAndroidOnPcRoute
  ItemIdRoute: typeof ItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/websites': {
      id: '/websites'
      path: '/websites'
      fullPath: '/websites'
      preLoaderRoute: typeof WebsitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$id': {
      id: '/item/$id'
      path: '/item/$id'
      fullPath: '/item/$id'
      preLoaderRoute: typeof ItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/android-on-pc': {
      id: '/guides/android-on-pc'
      path: '/guides/android-on-pc'
      fullPath: '/guides/android-on-pc'
      preLoaderRoute: typeof GuidesAndroidOnPcRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AiRoute: AiRoute,
  AppsRoute: AppsRoute,
  ContactRoute: ContactRoute,
  FavoritesRoute: FavoritesRoute,
  GamesRoute: GamesRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WebsitesRoute: WebsitesRoute,
  GuidesAndroidOnPcRoute: GuidesAndroidOnPcRoute,
  ItemIdRoute: ItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
